#vagrant-assignment
#derek ng a01055306
#to tim - no idea if this works, I ran out of time to run it :(


Vagrant.configure("2") do |config|
  config.vm.box = "base_4640"
  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/acit_admin_id_rsa"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.linked_clone = true
  end
  #Runs Nginx - Our Reverse Proxy
  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_APP_4640"
      vb.memory = 2048
    end
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "private_network", ip: "192.168.150.10"
    todoapp.vm.network "forwarded_port", guest: 80, host: 8888
    todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    todoapp.vm.provision "file", source: "./files/nginx.conf", destination: "/tmp/"
   
    #security settings, moving nginx, firewall, daemon
    todoapp.vm.provision "shell", inline: <<-SHELL
      setenforce 0
      dnf install -y nginx
      
      mv /tmp/nginx.conf /etc/nginx/nginx.conf

      firewall-cmd --zone=public --add-port=8888/tcp
      firewall-cmd --runtime-to-permanent

      systemctl daemon-reload
      
      systemctl enable nginx
      systemctl start nginx
      systemctl restart todoapp

    SHELL
  end
  
  #Runs NodeJS - Our App
  config.vm.define "todoservice" do |todoservice|
    todoservice.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_SERVICE_4640"
      vb.memory = 1024
    end
    todoservice.vm.hostname = "todoapp.bcit.local"
    todoservice.vm.network "private_network", ip: "192.168.150.20"
    todoservice.vm.synced_folder ".", "/vagrant", disabled: true    
   
    todoservice.vm.provision "file", source: "./files/todoapp.service", destination: "/tmp/todoapp.service"
    todoservice.vm.provision "file", source: "./files/todoapp.sh", destination: "/tmp/todoapp.sh"
    
    #setting password/todoapp user, locking pass, moving files, installing node
    #setting firewall, daemon restart
    todoservice.vm.provision "shell", inline: <<-SHELL
      PASSWORD="P@ssw0rd"
      
      setenforce 0
      useradd todoapp
      echo $PASSWORD | passwd --stdin todoapp 
      passwd -l todoapp

      mv /tmp/todoapp.service /etc/systemd/system/todoapp.service

      curl -sL https://rpm.nodesource.com/setup_14.x | sudo bash -

      dnf install -y git nodejs

      sudo -u todoapp bash /tmp/todoapp.sh

      firewall-cmd --zone=public --add-port=8080/tcp
      firewall-cmd --runtime-to-permanent

      systemctl daemon-reload
      systemctl enable todoapp 
      systemctl start todoapp
      systemctl restart todoapp
    SHELL
  end

  #Runs Mongo - Our DB
  config.vm.define "tododb" do |tododb|
    tododb.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_DB_4640"
      vb.memory = 1536
    end
    tododb.vm.hostname = "todoapp.bcit.local"
    tododb.vm.network "private_network", ip: "192.168.150.30"
    tododb.vm.synced_folder ".", "/vagrant", disabled: true    
    tododb.vm.provision "file", source: "./files/mongodb-org-4.4.repo", destination: "/tmp/mongodb-org-4.4.repo"
    tododb.vm.provision "file", source: "./files/ACIT4640", destination: "/tmp/ACIT4640"
    
    #security, install mongo and firewall settings
    tododb.vm.provision "shell", inline: <<-SHELL
      setenforce 0
      mv /tmp/mongodb-org-4.4.repo /etc/yum.repos.d/mongodb-org-4.4.repo

      dnf install -y mongodb-org

      firewall-cmd --zone=public --add-port=27017/tcp
      firewall-cmd --runtime-to-permanent
      
      systemctl daemon-reload
      systemctl enable mongod
      systemctl start mongod
      systemctl restart mongod

      sed -i 's#127.0.0.1#0.0.0.0#' /etc/mongod.conf

      export LANG=C
      mongorestore -d ACIT4640 /tmp/ACIT4640
    SHELL
  end
end
